name: Daily Paraguay News Summary

on:
  schedule:
    # 7 AM America/Asuncion = 11 AM UTC
    - cron: '0 11 * * *'
  workflow_dispatch: # allows manual run

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      OPEN_ROUTER_API_KEY: ${{ secrets.OPEN_ROUTER_API_KEY }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      GMAIL_SENDER: ${{ secrets.GMAIL_SENDER }}
      GMAIL_RECIPIENTS: ${{ secrets.GMAIL_RECIPIENTS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: 'latest'

      - name: 'Set up Python'
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'

      - name: Install the project
        run: uv sync

      - name: Run script
        run: uv run main.py
